### ISSUE TITLE
drawer 正在画的时候，如果 guesser 刷新页面，guesser 无法拿到最新的游戏画面

### ISSUE THREAD

**Issue by hyf0** [iheyunfei/draw-someting#1]
开始的解决思路是：每一次画面变动的时候都，都把画面同步到服务器。经过实践后，发现服务端在处理请求上会有相当大的延迟，客户端倒是没什么。经过分析，这样做，在 drawer 画画的时候，大约每秒60次请求打到服务器上，每次请求的大小都和一个图片差不多，导致服务器过载，无法处理。

**Comment by hyfdev** [comment]
经过上述实践得出的结论是，保证实时同步画面到服务器上的代码过高。如果在不保证实时的情况下，允许 guesser 有个 1-2s 的延迟情况下才拿到最新画面，性能上有了很大的提升。

现在的解决方法时，在 drawer 作画的时候，只同步画画的行为，保证在线的 guesser 的画面是同步的，在画画结束的时候，同步游戏画面，保证重连的 guesser 拿到最新画面，这样有个短小的延迟，但是算是当前比较优势的解决方法吧。
